@url_dev=http://localhost:8080/v1/api/
@apiKey=13d5613eda0df8f88288c8ec07c891ce89c7c50c38ec926f531e661f4d9c4608ab969bd82708f2f3f7bc614f77205da5b238ad3d86385c9d5c1b92633759e2c9
@clientId=64d6695f3fa8ad773d0ca74c
@authorization=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ2Njk1ZjNmYThhZDc3M2QwY2E3NGMiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE2OTE3NzQ1OTAsImV4cCI6MTY5MTk0NzM5MH0.yUTKUOlrK1uFoC0U96z2VpDbdtxDYv5v5QFQh2-mgQw

###
POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "name": "Shop 01",
  "email": "shop01@gmail.com",
  "password": "abc123"
}

###
POST {{url_dev}}shop/login
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "email" : "shop01@gmail.com",
  "password": "abc123"
}

###
POST {{url_dev}}shop/logout
x-client-id: {{clientId}}
x-api-key: {{apiKey}}
Content-Type: application/json
authorization: {{authorization}}

###
POST {{url_dev}}shop/refresh-token
x-client-id: {{clientId}} 
x-api-key: {{apiKey}}
Content-Type: application/json
authorization: {{authorization}}

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0NjYxMzhmOTMwOTcwMWJmMTU0YmEiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE2OTE2OTY0MTAsImV4cCI6MTY5MjMwMTIxMH0.rlx8nfIxhgOMo7B9kcUfo-9eXGgjBdjohYODNOfQpek"
}