@url_dev=http://localhost:8080/v1/api/
@apiKey=74ba94033115c363e1c9315733d7bb8df5c158386e48122b9b503ac2fe5f4408d4ed8ee337ef8b2f8f941f28b7a4686d199a6c4f08d7523006e1f47def4ad17e
@clientId = 64d466138f9309701bf154ba
@authorization = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0NjYxMzhmOTMwOTcwMWJmMTU0YmEiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE2OTE2OTY0MTAsImV4cCI6MTY5MTg2OTIxMH0.b5mjst2jWWqqBh9JUqDcJ9TUva9kjbXVNaT4zmqVOz8

###
POST {{url_dev}}shop/signup
Content-Type: application/json
x-api-key: {{apiKey}}

{
  "name": "Shop 01",
  "email": "shop01@gmail.com",
  "password": "abc123"
}

###
POST {{url_dev}}shop/login
x-api-key: {{apiKey}}
Content-Type: application/json

{
  "email" : "shop01@gmail.com",
  "password": "abc123"
}

###
POST {{url_dev}}shop/logout
x-client-id: {{clientId}}
x-api-key: {{apiKey}}
Content-Type: application/json
authorization: {{authorization}}

###
POST {{url_dev}}shop/refresh-token
x-client-id: {{clientId}} 
x-api-key: {{apiKey}}
Content-Type: application/json
authorization: {{authorization}}

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGQ0NjYxMzhmOTMwOTcwMWJmMTU0YmEiLCJlbWFpbCI6InNob3AwMUBnbWFpbC5jb20iLCJpYXQiOjE2OTE2OTY0MTAsImV4cCI6MTY5MjMwMTIxMH0.rlx8nfIxhgOMo7B9kcUfo-9eXGgjBdjohYODNOfQpek"
}